[general]
active = 1
#   0: development
#   1: docker
#   2: production
#   3: qa
port = 8080

[general.redis]
port = "6379"

[[env-map]]
index = 0
type = "development"

[[env-map]]
index = 1
type = "docker"

[[env-map]]
index = 2
type = "production"

[[env-map]]
index = 3
type = "qa"


[api]
api = "/api"






